//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cb.Localization.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cb.Localization.resources.labels", typeof(labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        internal static string admin_user_not_exist {
            get {
                return ResourceManager.GetString("admin_user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm thành công.
        /// </summary>
        internal static string alert_addtocart_succes {
            get {
                return ResourceManager.GetString("alert_addtocart_succes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên (Tab tiếng việt)..
        /// </summary>
        internal static string alert_empty_name {
            get {
                return ResourceManager.GetString("alert_empty_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên (Tab tiếng Anh)..
        /// </summary>
        internal static string alert_empty_name_english {
            get {
                return ResourceManager.GetString("alert_empty_name_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ email.&lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string alert_login_empty_email {
            get {
                return ResourceManager.GetString("alert_login_empty_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mật khẩu&lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string alert_login_empty_pass {
            get {
                return ResourceManager.GetString("alert_login_empty_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên đăng nhập&lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string alert_login_empty_username {
            get {
                return ResourceManager.GetString("alert_login_empty_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hay mật khẩu không đúng &lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string alert_login_error {
            get {
                return ResourceManager.GetString("alert_login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email không hợp lệ.&lt;p&gt;&lt;/p&gt;.
        /// </summary>
        internal static string alert_login_invalid_email {
            get {
                return ResourceManager.GetString("alert_login_invalid_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi mail liên hệ thành công.
        /// </summary>
        internal static string alert_message_contact {
            get {
                return ResourceManager.GetString("alert_message_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chúng tôi đã gửi email chứa mật khẩu đến hộp thư của bạn.
        /// </summary>
        internal static string alert_message_forgot_pass {
            get {
                return ResourceManager.GetString("alert_message_forgot_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi IdeaCenter thành công.
        /// </summary>
        internal static string alert_message_idea_center {
            get {
                return ResourceManager.GetString("alert_message_idea_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đăng ký thành công.&lt;br /&gt;Chúng tôi sẽ cập nhật thông tin của Bạn trong vòng 24 giờ..
        /// </summary>
        internal static string alert_message_regist_success {
            get {
                return ResourceManager.GetString("alert_message_regist_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần đăng nhập trước khi thanh toán.
        /// </summary>
        internal static string alert_need_login {
            get {
                return ResourceManager.GetString("alert_need_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến dung tích phải lớn hơn hoặc bằng từ dung tích.
        /// </summary>
        internal static string alert_product_cmp_capacity {
            get {
                return ResourceManager.GetString("alert_product_cmp_capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày phải lớn hơn hoặc bằng từ ngày.
        /// </summary>
        internal static string alert_product_cmp_date {
            get {
                return ResourceManager.GetString("alert_product_cmp_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến giá phải lớn hơn hoặc bằng từ giá.
        /// </summary>
        internal static string alert_product_cmp_price {
            get {
                return ResourceManager.GetString("alert_product_cmp_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến trọng lượng phải lớn hơn từ trọng lượng.
        /// </summary>
        internal static string alert_product_cmp_weight {
            get {
                return ResourceManager.GetString("alert_product_cmp_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string btn_login {
            get {
                return ResourceManager.GetString("btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        internal static string btn_sendMail {
            get {
                return ResourceManager.GetString("btn_sendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm lại.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo dưới.
        /// </summary>
        internal static string enuBannerPosition_logo_bottom {
            get {
                return ResourceManager.GetString("enuBannerPosition_logo_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo trái.
        /// </summary>
        internal static string enuBannerPosition_logo_left {
            get {
                return ResourceManager.GetString("enuBannerPosition_logo_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chính.
        /// </summary>
        internal static string enuBannerPosition_main {
            get {
                return ResourceManager.GetString("enuBannerPosition_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNĐ.
        /// </summary>
        internal static string enuCostId_dong {
            get {
                return ResourceManager.GetString("enuCostId_dong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lượng.
        /// </summary>
        internal static string enuCostId_luongSJC {
            get {
                return ResourceManager.GetString("enuCostId_luongSJC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tỉ VNĐ.
        /// </summary>
        internal static string enuCostId_tidong {
            get {
                return ResourceManager.GetString("enuCostId_tidong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to triệu.
        /// </summary>
        internal static string enuCostId_trieudong {
            get {
                return ResourceManager.GetString("enuCostId_trieudong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string enuCostId_usd {
            get {
                return ResourceManager.GetString("enuCostId_usd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string enulogoPosition_logo_left {
            get {
                return ResourceManager.GetString("enulogoPosition_logo_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string fm_name1 {
            get {
                return ResourceManager.GetString("fm_name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã an toàn.
        /// </summary>
        internal static string ltr_SecurityCode {
            get {
                return ResourceManager.GetString("ltr_SecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string ltrAddress {
            get {
                return ResourceManager.GetString("ltrAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string ltrChangedPass {
            get {
                return ResourceManager.GetString("ltrChangedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty.
        /// </summary>
        internal static string ltrCompanyName {
            get {
                return ResourceManager.GetString("ltrCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nhắn.
        /// </summary>
        internal static string ltrfm_message {
            get {
                return ResourceManager.GetString("ltrfm_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang quản trị.
        /// </summary>
        internal static string ltrHeaderAdminpage {
            get {
                return ResourceManager.GetString("ltrHeaderAdminpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        internal static string ltrHeaderAgent {
            get {
                return ResourceManager.GetString("ltrHeaderAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string ltrHeaderHome {
            get {
                return ResourceManager.GetString("ltrHeaderHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string ltrHeaderLogin {
            get {
                return ResourceManager.GetString("ltrHeaderLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string ltrHeaderLogout {
            get {
                return ResourceManager.GetString("ltrHeaderLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký.
        /// </summary>
        internal static string ltrHeaderRegister {
            get {
                return ResourceManager.GetString("ltrHeaderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string ltrHeaderSearch {
            get {
                return ResourceManager.GetString("ltrHeaderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string ltrHeaderService {
            get {
                return ResourceManager.GetString("ltrHeaderService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        internal static string ltrLangue {
            get {
                return ResourceManager.GetString("ltrLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string ltrLienhe {
            get {
                return ResourceManager.GetString("ltrLienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch vụ.
        /// </summary>
        internal static string ltrListServices {
            get {
                return ResourceManager.GetString("ltrListServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát .
        /// </summary>
        internal static string ltrLogout {
            get {
                return ResourceManager.GetString("ltrLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức mới nhất.
        /// </summary>
        internal static string ltrNewsDetail {
            get {
                return ResourceManager.GetString("ltrNewsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức mới nhất.
        /// </summary>
        internal static string ltrNewsHeaderHome {
            get {
                return ResourceManager.GetString("ltrNewsHeaderHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string ltrPhone {
            get {
                return ResourceManager.GetString("ltrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string statement_delete {
            get {
                return ResourceManager.GetString("statement_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string statement_email {
            get {
                return ResourceManager.GetString("statement_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string statement_fax {
            get {
                return ResourceManager.GetString("statement_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        internal static string statement_forgot_pass {
            get {
                return ResourceManager.GetString("statement_forgot_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string statement_from_date {
            get {
                return ResourceManager.GetString("statement_from_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá từ.
        /// </summary>
        internal static string statement_from_price {
            get {
                return ResourceManager.GetString("statement_from_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        internal static string statement_have {
            get {
                return ResourceManager.GetString("statement_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập với vai trò.
        /// </summary>
        internal static string statement_loginas {
            get {
                return ResourceManager.GetString("statement_loginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa lại.
        /// </summary>
        internal static string str_admin_unpublish {
            get {
                return ResourceManager.GetString("str_admin_unpublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string strAdminAddNew {
            get {
                return ResourceManager.GetString("strAdminAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        internal static string strAdminPublish {
            get {
                return ResourceManager.GetString("strAdminPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu hình.
        /// </summary>
        internal static string strConfig {
            get {
                return ResourceManager.GetString("strConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ.
        /// </summary>
        internal static string strContact {
            get {
                return ResourceManager.GetString("strContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string strDelete {
            get {
                return ResourceManager.GetString("strDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        internal static string strDetail {
            get {
                return ResourceManager.GetString("strDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        internal static string strEdit {
            get {
                return ResourceManager.GetString("strEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa danh mục cấp 1.
        /// </summary>
        internal static string strEditNewsCategory {
            get {
                return ResourceManager.GetString("strEditNewsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa nhà cung cấp.
        /// </summary>
        internal static string strEditProvider {
            get {
                return ResourceManager.GetString("strEditProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string strFind {
            get {
                return ResourceManager.GetString("strFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản ly danh mục.
        /// </summary>
        internal static string strHeaderCate {
            get {
                return ResourceManager.GetString("strHeaderCate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục cấp 1.
        /// </summary>
        internal static string strHeaderCateCategory {
            get {
                return ResourceManager.GetString("strHeaderCateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý danh mục cấp 0.
        /// </summary>
        internal static string strHeaderCateCategory0 {
            get {
                return ResourceManager.GetString("strHeaderCateCategory0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý dịch vụ.
        /// </summary>
        internal static string strHeaderServices {
            get {
                return ResourceManager.GetString("strHeaderServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        internal static string strIgnore {
            get {
                return ResourceManager.GetString("strIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu.
        /// </summary>
        internal static string strIntro {
            get {
                return ResourceManager.GetString("strIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string strLogin {
            get {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        internal static string strMenu {
            get {
                return ResourceManager.GetString("strMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        internal static string strOrdering {
            get {
                return ResourceManager.GetString("strOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string strServicesCategory {
            get {
                return ResourceManager.GetString("strServicesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cập nhật.
        /// </summary>
        internal static string strUpdateDate {
            get {
                return ResourceManager.GetString("strUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string strVietName {
            get {
                return ResourceManager.GetString("strVietName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sơ đồ website.
        /// </summary>
        internal static string strWeb {
            get {
                return ResourceManager.GetString("strWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string Telefon1 {
            get {
                return ResourceManager.GetString("Telefon1", resourceCulture);
            }
        }
    }
}
